/**
 * HOLLYWOOD RISING - Acting School Database
 * 70 Realistic Acting Courses across 6 Permanent Talents:
 * Acting, Voice, Comedy, Drama, Action, Dancing
 */

import { ActingCourse, TalentCategory } from '../types/game';

export const ACTING_COURSES_POOL: ActingCourse[] = [
  // ================= ACTING COURSES (1-12) =================
  {
    id: 'course_act_1',
    name: 'Intro to Scene Study & Stage Craft',
    teacher: 'Arthur Vance (Lee Strasberg Institute)',
    description: 'Master stage presence, eye line control, and basic textual interpretation.',
    category: 'acting',
    cost: 150,
    durationWeeks: 1,
    weeklyEnergyCost: 5,
    talentReward: { talent: 'acting', amount: 3 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_2',
    name: 'Stella Adler Technique & Imagination',
    teacher: 'Eleanor Vance',
    description: 'Learn to build rich fictional worlds using Adler’s core principles.',
    category: 'acting',
    cost: 350,
    durationWeeks: 2,
    weeklyEnergyCost: 8,
    talentReward: { talent: 'acting', amount: 5 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_3',
    name: 'Sanford Meisner Repetition & Truth',
    teacher: 'David Sterling',
    description: 'Focus on living truthfully under imaginary circumstances through active repetition.',
    category: 'acting',
    cost: 750,
    durationWeeks: 4,
    weeklyEnergyCost: 12,
    talentReward: { talent: 'acting', amount: 8 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_4',
    name: 'Stanislavski Emotion Memory & Objectives',
    teacher: 'Prof. Viktor Kren',
    description: 'Uncover psychological objectives and emotional triggers for realistic screen acting.',
    category: 'acting',
    cost: 1200,
    durationWeeks: 6,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'acting', amount: 11 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_5',
    name: 'On-Camera Cold Reading & Audition Prep',
    teacher: 'Samantha Hayes (Casting Director)',
    description: 'Deliver instant, compelling audition takes under high studio pressure.',
    category: 'acting',
    cost: 1800,
    durationWeeks: 5,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'acting', amount: 12 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_6',
    name: 'Uta Hagen Object Exercises & Continuity',
    teacher: 'Marcus Brody',
    description: 'Maintain prop continuity and spatial awareness for film multi-angle takes.',
    category: 'acting',
    cost: 2500,
    durationWeeks: 8,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'acting', amount: 14 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_7',
    name: 'Screen Acting for IMAX & 70mm Productions',
    teacher: 'Christopher Vance (DGA Director)',
    description: 'Subtle micro-expressions calibrated specifically for massive widescreen canvases.',
    category: 'acting',
    cost: 4500,
    durationWeeks: 10,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'acting', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_8',
    name: 'Method Acting Inner Transformation',
    teacher: 'Gareth Thorne (Oscar Nominee Coach)',
    description: 'Deep psychological immersion into complex, transformative screen personas.',
    category: 'acting',
    cost: 7500,
    durationWeeks: 14,
    weeklyEnergyCost: 22,
    talentReward: { talent: 'acting', amount: 18 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_act_9',
    name: 'Masterclass in Lead Actor Presence & Charisma',
    teacher: 'Sir Alistair Montgomery',
    description: 'Commanding total screen attention in multi-million dollar studio productions.',
    category: 'acting',
    cost: 12000,
    durationWeeks: 20,
    weeklyEnergyCost: 25,
    talentReward: { talent: 'acting', amount: 22 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_act_10',
    name: 'Oscar-Caliber Character Deconstruction',
    teacher: 'Helen Mirren Conservatory Faculty',
    description: 'Subversive choices, vocal nuances, and physical mannerisms for award-season roles.',
    category: 'acting',
    cost: 18000,
    durationWeeks: 28,
    weeklyEnergyCost: 28,
    talentReward: { talent: 'acting', amount: 25 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_act_11',
    name: 'Green Screen & CGI Suit Performance',
    teacher: 'Andy Serkis Performance Capture Lab',
    description: 'Acting inside virtual production volumes and motion capture suits.',
    category: 'acting',
    cost: 3200,
    durationWeeks: 6,
    weeklyEnergyCost: 16,
    talentReward: { talent: 'acting', amount: 13 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_act_12',
    name: 'Period Piece Etiquette & Historical Drama',
    teacher: 'Lady Beatrice Sterling',
    description: 'Authentic posture, diction, and emotional restraint for 18th-century epics.',
    category: 'acting',
    cost: 2800,
    durationWeeks: 8,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'acting', amount: 14 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },

  // ================= VOICE COURSES (13-24) =================
  {
    id: 'course_voc_1',
    name: 'Vocal Projection & Diaphragmatic Breath',
    teacher: 'Clara Oswald',
    description: 'Build core vocal stamina, breath support, and resonance for long filming days.',
    category: 'voice',
    cost: 200,
    durationWeeks: 1,
    weeklyEnergyCost: 5,
    talentReward: { talent: 'voice', amount: 4 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_2',
    name: 'Standard American Accent & Diction',
    teacher: 'Dr. Robert Lang',
    description: 'Eliminate regional accents to achieve flawless, neutral studio pronunciation.',
    category: 'voice',
    cost: 450,
    durationWeeks: 3,
    weeklyEnergyCost: 10,
    talentReward: { talent: 'voice', amount: 7 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_3',
    name: 'Dialects: British RP, Cockney & Irish',
    teacher: 'Fiona MacLeod',
    description: 'Master authentic United Kingdom dialects for international film productions.',
    category: 'voice',
    cost: 950,
    durationWeeks: 5,
    weeklyEnergyCost: 12,
    talentReward: { talent: 'voice', amount: 10 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_4',
    name: 'Voice Acting for Animated Features & Anime',
    teacher: 'Troy Baker Voice Studio',
    description: 'Create dynamic, expressive vocal characters for high-budget animated films.',
    category: 'voice',
    cost: 1600,
    durationWeeks: 6,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'voice', amount: 12 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_5',
    name: 'Video Game Motion Capture & Battle Cries',
    teacher: 'Laura Bailey Voice Lab',
    description: 'Vocal safety during strenuous screaming, grunting, and action sequences.',
    category: 'voice',
    cost: 2200,
    durationWeeks: 7,
    weeklyEnergyCost: 16,
    talentReward: { talent: 'voice', amount: 13 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_6',
    name: 'ADR & Post-Production Studio Dubbing',
    teacher: 'Gary Newman (Sound Supervisor)',
    description: 'Flawlessly sync vocal replacements with live-action lip movements in post.',
    category: 'voice',
    cost: 3500,
    durationWeeks: 8,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'voice', amount: 15 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_7',
    name: 'Shakespearian Verse & iambic Pentameter',
    teacher: 'Royal Shakespeare Company Alum',
    description: 'Unlock rhythm, cadence, and gravitas for classical dramatic dialogue.',
    category: 'voice',
    cost: 5000,
    durationWeeks: 12,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'voice', amount: 17 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_8',
    name: 'Global Accents: Transatlantic, Slavic & French',
    teacher: 'Prof. Jean-Paul Laurent',
    description: 'Expand your international dialect repertoire for espionage thriller casting.',
    category: 'voice',
    cost: 7000,
    durationWeeks: 15,
    weeklyEnergyCost: 22,
    talentReward: { talent: 'voice', amount: 19 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_voc_9',
    name: 'Audiobook Narration & Multi-Character Voice',
    teacher: 'Audible Master Producer',
    description: 'Sustain distinct vocal identities across 10+ characters in single solo takes.',
    category: 'voice',
    cost: 10000,
    durationWeeks: 18,
    weeklyEnergyCost: 24,
    talentReward: { talent: 'voice', amount: 21 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_voc_10',
    name: 'Masterclass in Cinematic Voice Mastery',
    teacher: 'Morgan Freeman Mentorship Guild',
    description: 'Deep, resonant, iconic voice delivery for film trailers and studio lead roles.',
    category: 'voice',
    cost: 16000,
    durationWeeks: 25,
    weeklyEnergyCost: 26,
    talentReward: { talent: 'voice', amount: 24 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_voc_11',
    name: 'Singing Voice Control for Feature Film Hits',
    teacher: 'Bel Canto Opera Coach',
    description: 'Pitch accuracy, vibrato, and vocal control for dramatic singing roles.',
    category: 'voice',
    cost: 4000,
    durationWeeks: 10,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'voice', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_voc_12',
    name: 'Monster & Creature Vocal Sound Effects',
    teacher: 'ILM Sound Effects Studio',
    description: 'Specialized vocal techniques for scifi and horror monster soundscapes.',
    category: 'voice',
    cost: 2800,
    durationWeeks: 6,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'voice', amount: 13 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },

  // ================= COMEDY COURSES (25-36) =================
  {
    id: 'course_com_1',
    name: 'Groundlings Improv & Spontaneity 101',
    teacher: 'Molly Shannon Alumni',
    description: 'Say "Yes, And..." and trust your comic instincts in unexpected scenes.',
    category: 'comedy',
    cost: 250,
    durationWeeks: 2,
    weeklyEnergyCost: 8,
    talentReward: { talent: 'comedy', amount: 5 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_2',
    name: 'Upright Citizens Brigade Character Comedy',
    teacher: 'Matt Besser Studio',
    description: 'Create memorable, quirky comedy characters with distinct body language.',
    category: 'comedy',
    cost: 600,
    durationWeeks: 3,
    weeklyEnergyCost: 10,
    talentReward: { talent: 'comedy', amount: 8 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_3',
    name: 'Sitcom Timing & Multi-Cam Studio Audience',
    teacher: 'Chuck Lorre Showrunner Lab',
    description: 'Master joke setups, punchline pauses, and studio audience rhythm.',
    category: 'comedy',
    cost: 1400,
    durationWeeks: 5,
    weeklyEnergyCost: 14,
    talentReward: { talent: 'comedy', amount: 11 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_4',
    name: 'Physical Comedy, Slapstick & Double Takes',
    teacher: 'Buster Keaton Comedy Institute',
    description: 'Precision physical comedy, trips, drops, and hilarious reactions.',
    category: 'comedy',
    cost: 2200,
    durationWeeks: 7,
    weeklyEnergyCost: 16,
    talentReward: { talent: 'comedy', amount: 13 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_5',
    name: 'Mockumentary Style & Subtle Dry Humor',
    teacher: 'The Office Show Writer',
    description: 'Mastering deadpan glances at camera and understated comedic deadpan.',
    category: 'comedy',
    cost: 3200,
    durationWeeks: 8,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'comedy', amount: 15 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_6',
    name: 'Stand-Up Comedy Writing & Punchline Polish',
    teacher: 'Comedy Cellar Veteran',
    description: 'Drafting original comedic material and refining punchlines for film scripts.',
    category: 'comedy',
    cost: 4800,
    durationWeeks: 10,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'comedy', amount: 17 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_7',
    name: 'Rom-Com Lead Chemistry & Witty Banter',
    teacher: 'Nora Ephron Screenwriter Guild',
    description: 'Charm, comedic timing, and snappy romantic banter in studio blockbusters.',
    category: 'comedy',
    cost: 6800,
    durationWeeks: 12,
    weeklyEnergyCost: 21,
    talentReward: { talent: 'comedy', amount: 19 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_com_8',
    name: 'Satire, Parody & Dark Comedy Masterclass',
    teacher: 'Armando Iannucci Comedy Lab',
    description: 'Navigating high-level political satire, irony, and subversive comedic writing.',
    category: 'comedy',
    cost: 9500,
    durationWeeks: 16,
    weeklyEnergyCost: 23,
    talentReward: { talent: 'comedy', amount: 21 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_com_9',
    name: 'Masterclass in Comedy Lead Stardom',
    teacher: 'Jim Carrey & Steve Martin Mentors',
    description: 'Unbridled comedic energy and legendary box-office comedy presence.',
    category: 'comedy',
    cost: 15000,
    durationWeeks: 24,
    weeklyEnergyCost: 26,
    talentReward: { talent: 'comedy', amount: 24 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_com_10',
    name: 'Snappy Callback & Improvisational Polish',
    teacher: 'Second City Chicago Director',
    description: 'On-set ad-libbing that makes film directors keep the camera rolling.',
    category: 'comedy',
    cost: 2800,
    durationWeeks: 6,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'comedy', amount: 14 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_11',
    name: 'Parody & Impersonation Technique',
    teacher: 'SNL Impression Specialist',
    description: 'Capturing celebrity mannerisms, vocal cadence, and comedic caricatures.',
    category: 'comedy',
    cost: 3800,
    durationWeeks: 8,
    weeklyEnergyCost: 17,
    talentReward: { talent: 'comedy', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_com_12',
    name: 'Absurdist Comedy & Surrealist Performance',
    teacher: 'Monty Python Academy',
    description: 'Embracing surreal, bizarre comedy concepts with unwavering commitment.',
    category: 'comedy',
    cost: 5500,
    durationWeeks: 10,
    weeklyEnergyCost: 19,
    talentReward: { talent: 'comedy', amount: 18 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },

  // ================= DRAMA COURSES (37-48) =================
  {
    id: 'course_dra_1',
    name: 'Monologue Intensity & Emotional Access',
    teacher: 'Sarah Connor (Juilliard Faculty)',
    description: 'Unlocking raw vulnerability and tears-on-command for auditions.',
    category: 'drama',
    cost: 300,
    durationWeeks: 2,
    weeklyEnergyCost: 8,
    talentReward: { talent: 'drama', amount: 5 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_2',
    name: 'Tragic Scene Study: Shakespeare & Chekhov',
    teacher: 'Prof. Edward Vance',
    description: 'Analyzing high-stakes dramatic texts and personal loss themes.',
    category: 'drama',
    cost: 800,
    durationWeeks: 4,
    weeklyEnergyCost: 12,
    talentReward: { talent: 'drama', amount: 9 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_3',
    name: 'Psychological Thriller & Dark Persona Acting',
    teacher: 'David Fincher Character Coach',
    description: 'Portraying complex, morally ambiguous anti-heroes and antagonists.',
    category: 'drama',
    cost: 1800,
    durationWeeks: 6,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'drama', amount: 12 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_4',
    name: 'Grief, Loss & Trauma On Screen',
    teacher: 'Dr. Evelyn Reed (Drama Therapist)',
    description: 'Safely tapping into deep emotional grief while maintaining personal mental safety.',
    category: 'drama',
    cost: 2800,
    durationWeeks: 8,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'drama', amount: 14 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_5',
    name: 'Courtroom Drama & Monologue Deliveries',
    teacher: 'Judge Richard Sterling (Legal Advisor)',
    description: 'High-octane speeches, closing arguments, and intense cross-examinations.',
    category: 'drama',
    cost: 4200,
    durationWeeks: 9,
    weeklyEnergyCost: 19,
    talentReward: { talent: 'drama', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_6',
    name: 'Intimacy & High-Emotion Screen Chemistry',
    teacher: 'SAG Certified Intimacy Coordinator',
    description: 'Building authentic romantic tension and dramatic vulnerability safely on set.',
    category: 'drama',
    cost: 6000,
    durationWeeks: 12,
    weeklyEnergyCost: 21,
    talentReward: { talent: 'drama', amount: 18 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_dra_7',
    name: 'Biopic Immersion & Real-Person Dramatization',
    teacher: 'Academy Award Biopic Specialist',
    description: 'Studying archival recordings to embody historic figures without caricature.',
    category: 'drama',
    cost: 8500,
    durationWeeks: 15,
    weeklyEnergyCost: 23,
    talentReward: { talent: 'drama', amount: 20 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_dra_8',
    name: 'Royal Conservatory Dramatic Masterclass',
    teacher: 'Dame Judi Dench Masterclass',
    description: 'Uncompromising dramatic excellence for Oscar-contending cinema.',
    category: 'drama',
    cost: 14000,
    durationWeeks: 22,
    weeklyEnergyCost: 25,
    talentReward: { talent: 'drama', amount: 23 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_dra_9',
    name: 'Subtext & Silence: The Art of Unspoken Drama',
    teacher: 'Ingmar Bergman Retrospective Fellow',
    description: 'Conveying heartbreaking dramatic narratives through glance and stillness.',
    category: 'drama',
    cost: 5000,
    durationWeeks: 10,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'drama', amount: 17 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_10',
    name: 'Mob Epics & Crime Syndicate Dramatics',
    teacher: 'Martin Scorsese Regular Coach',
    description: 'Grit, betrayal, and explosive emotional outbursts in mob cinema.',
    category: 'drama',
    cost: 7200,
    durationWeeks: 14,
    weeklyEnergyCost: 22,
    talentReward: { talent: 'drama', amount: 19 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_dra_11',
    name: 'War Epics & Combat Stress Dramatics',
    teacher: 'Military Film Advisor Capt. Vance',
    description: 'Portraying battlefield camaraderie, PTSD, and raw survival instinct.',
    category: 'drama',
    cost: 4800,
    durationWeeks: 10,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'drama', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dra_12',
    name: 'Indie Cinema Naturalism & Micro-Budget Drama',
    teacher: 'Sundance Film Festival Winner',
    description: 'Hyper-realistic, unvarnished dramatic takes for indie feature films.',
    category: 'drama',
    cost: 2100,
    durationWeeks: 5,
    weeklyEnergyCost: 14,
    talentReward: { talent: 'drama', amount: 11 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },

  // ================= ACTION COURSES (49-60) =================
  {
    id: 'course_actn_1',
    name: 'Stage Combat 101 & Safe Slaps/Punches',
    teacher: 'Hollywood Stunt Guild Instructor',
    description: 'Camera-angle deception, reaction timing, and safe physical choreography.',
    category: 'action',
    cost: 350,
    durationWeeks: 2,
    weeklyEnergyCost: 10,
    talentReward: { talent: 'action', amount: 5 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_2',
    name: 'Swordplay & Fencing for Fantasy Epics',
    teacher: 'Master Sword Master Pierre',
    description: 'Broadsword, rapier, and dagger footwork for historical action films.',
    category: 'action',
    cost: 900,
    durationWeeks: 4,
    weeklyEnergyCost: 14,
    talentReward: { talent: 'action', amount: 9 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_3',
    name: 'Martial Arts Choreography & Kickboxing',
    teacher: '8th Dan Black Belt Sensei Lee',
    description: 'High kicks, block combinations, and fluid martial arts combat flow.',
    category: 'action',
    cost: 2000,
    durationWeeks: 6,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'action', amount: 12 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_4',
    name: 'Tactical Firearms & SWAT Room Clearance',
    teacher: 'Ex-Navy SEAL Tactical Advisor',
    description: 'Handgun reloads, rifle stances, and realistic military tactical maneuvers.',
    category: 'action',
    cost: 3800,
    durationWeeks: 8,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'action', amount: 15 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_5',
    name: 'High-Speed Precision Stunt Driving',
    teacher: 'Fast & Furious Stunt Coordinator',
    description: 'J-turns, drifting, and high-speed precision driving on closed studio tracks.',
    category: 'action',
    cost: 6500,
    durationWeeks: 10,
    weeklyEnergyCost: 22,
    talentReward: { talent: 'action', amount: 17 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_6',
    name: 'Wirework, High Falls & Aerial Acrobatics',
    teacher: 'Hong Kong Stunt Team Legend',
    description: 'Harness wirework for superhero landings, high falls, and mid-air fights.',
    category: 'action',
    cost: 9500,
    durationWeeks: 14,
    weeklyEnergyCost: 24,
    talentReward: { talent: 'action', amount: 20 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_actn_7',
    name: 'John Wick Gun-Fu Combat Mastery',
    teacher: '87eleven Action Design Studio',
    description: 'Close-quarters gun-fu, judo throws, and long continuous action takes.',
    category: 'action',
    cost: 13000,
    durationWeeks: 18,
    weeklyEnergyCost: 26,
    talentReward: { talent: 'action', amount: 22 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_actn_8',
    name: 'Masterclass in Blockbuster Action Stardom',
    teacher: 'Tom Cruise Stunt Rigging Mentor',
    description: 'Performing your own high-risk stunts in multi-hundred million dollar tentpoles.',
    category: 'action',
    cost: 22000,
    durationWeeks: 30,
    weeklyEnergyCost: 30,
    talentReward: { talent: 'action', amount: 25 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_actn_9',
    name: 'Parkour & Urban Free Running for Cinema',
    teacher: 'French Yamakasi Founder',
    description: 'Rooftop jumps, wall runs, and fluid obstacle navigation for thrillers.',
    category: 'action',
    cost: 3200,
    durationWeeks: 6,
    weeklyEnergyCost: 18,
    talentReward: { talent: 'action', amount: 13 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_10',
    name: 'Underwater Stunt & Scuba Performance',
    teacher: 'Avatar Water Stunt Team',
    description: 'Breath-holding underwater combat and motion capture in deep studio tanks.',
    category: 'action',
    cost: 5800,
    durationWeeks: 10,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'action', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_11',
    name: 'Archery & Medieval Warfare Choreography',
    teacher: 'Lord of the Rings Stunt Team',
    description: 'Rapid-fire bow drawing, horseback archery, and medieval shield walls.',
    category: 'action',
    cost: 4500,
    durationWeeks: 8,
    weeklyEnergyCost: 19,
    talentReward: { talent: 'action', amount: 15 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_actn_12',
    name: 'Explosion Escape & Fire Suit Safety',
    teacher: 'Pyro Stunt Safety Director',
    description: 'Navigating pyrotechnic explosions, squibs, and controlled fire stunts safely.',
    category: 'action',
    cost: 7800,
    durationWeeks: 12,
    weeklyEnergyCost: 22,
    talentReward: { talent: 'action', amount: 18 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },

  // ================= DANCING COURSES (61-70) =================
  {
    id: 'course_dnc_1',
    name: 'Ballroom & Waltz Etiquette Fundamentals',
    teacher: 'Vienna Dance Academy Alumni',
    description: 'Posture, leading, and elegant waltz steps for formal ballroom film scenes.',
    category: 'dancing',
    cost: 250,
    durationWeeks: 2,
    weeklyEnergyCost: 8,
    talentReward: { talent: 'dancing', amount: 5 },
    difficulty: 'Beginner',
    requiresUnionMember: false,
  },
  {
    id: 'course_dnc_2',
    name: 'Salsa, Tango & Latin Passion Movement',
    teacher: 'Argentine Tango Master',
    description: 'Rhythmic passion, hip isolation, and intense partner connection.',
    category: 'dancing',
    cost: 700,
    durationWeeks: 4,
    weeklyEnergyCost: 12,
    talentReward: { talent: 'dancing', amount: 9 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_dnc_3',
    name: 'Broadway Tap & Jazz Choreography',
    teacher: 'Radio City Rockette Choreographer',
    description: 'Snappy tap rhythm, jazz turns, and stage musical dance stamina.',
    category: 'dancing',
    cost: 1600,
    durationWeeks: 5,
    weeklyEnergyCost: 15,
    talentReward: { talent: 'dancing', amount: 12 },
    difficulty: 'Intermediate',
    requiresUnionMember: false,
  },
  {
    id: 'course_dnc_4',
    name: 'Commercial Hip-Hop & Music Video Movement',
    teacher: 'LA Millennium Dance Complex Director',
    description: 'Hard-hitting hip-hop choreography, pop-locking, and camera-facing grooves.',
    category: 'dancing',
    cost: 2800,
    durationWeeks: 7,
    weeklyEnergyCost: 17,
    talentReward: { talent: 'dancing', amount: 14 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dnc_5',
    name: 'Ballet Grace, pirouette & Extension',
    teacher: 'Bolshoi Ballet Soloist',
    description: 'Precision ballet technique, poise, and body control for period masterpieces.',
    category: 'dancing',
    cost: 4500,
    durationWeeks: 10,
    weeklyEnergyCost: 20,
    talentReward: { talent: 'dancing', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dnc_6',
    name: 'Contemporary Floorwork & Emotional Expression',
    teacher: 'Alvin Ailey Principal Dancer',
    description: 'Fluid contemporary dance interpreting complex emotional states.',
    category: 'dancing',
    cost: 6500,
    durationWeeks: 12,
    weeklyEnergyCost: 21,
    talentReward: { talent: 'dancing', amount: 18 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_dnc_7',
    name: 'Hollywood Musical Feature Film Lead Dancing',
    teacher: 'La La Land Head Choreographer',
    description: 'Sweeping continuous-shot musical dance routines for lead film stars.',
    category: 'dancing',
    cost: 11000,
    durationWeeks: 16,
    weeklyEnergyCost: 24,
    talentReward: { talent: 'dancing', amount: 22 },
    difficulty: 'Elite',
    requiresUnionMember: true,
  },
  {
    id: 'course_dnc_8',
    name: 'Masterclass in Global Dance & Physical Poise',
    teacher: 'Mikhail Baryshnikov Academy Fellow',
    description: 'Virtuoso dance technique commanding global respect across genres.',
    category: 'dancing',
    cost: 17000,
    durationWeeks: 25,
    weeklyEnergyCost: 27,
    talentReward: { talent: 'dancing', amount: 25 },
    difficulty: 'Masterclass',
    requiresUnionMember: true,
  },
  {
    id: 'course_dnc_9',
    name: 'Cabaret & Burlesque Stage Presence',
    teacher: 'Paris Moulin Rouge Lead',
    description: 'Alluring stage presence, feather prop manipulation, and vintage cabaret.',
    category: 'dancing',
    cost: 3800,
    durationWeeks: 8,
    weeklyEnergyCost: 16,
    talentReward: { talent: 'dancing', amount: 14 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
  {
    id: 'course_dnc_10',
    name: 'Breakdancing & Street Power Moves',
    teacher: 'Red Bull BC One World Champion',
    description: 'Windmills, freezes, and headspins for youth culture and street dance films.',
    category: 'dancing',
    cost: 5000,
    durationWeeks: 9,
    weeklyEnergyCost: 19,
    talentReward: { talent: 'dancing', amount: 16 },
    difficulty: 'Advanced',
    requiresUnionMember: false,
  },
];

/**
 * Generate up to 4 random available courses for the weekly Acting School catalogue.
 * COMPLETED courses are graduated — never offered again. Active courses are
 * excluded so you can't double-enroll. When the catalog is exhausted the
 * school simply has nothing left to teach (no fallback to completed courses).
 */
export function generateWeeklyCourses(completedCourseIds: string[] = [], activeCourseIds: string[] = []): ActingCourse[] {
  const excluded = new Set([...completedCourseIds, ...activeCourseIds]);
  const availablePool = ACTING_COURSES_POOL.filter(c => !excluded.has(c.id));

  const shuffled = [...availablePool].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 4);
}
