/**
 * HOLLYWOOD RISING - World System Database (Phase 3)
 * Comprehensive initial datasets for all 15 World Ecosystem Systems.
 */

import {
  BoxOfficeItem,
  StreamingPlatform,
  BankrollOpportunity,
  TvStation,
  RadioStation,
  SocialAccount,
  SocialPost,
  HiredWriter,
  AwardItem,
  LawFirm,
  CryptoCoin,
  CryptoWhale,
  StarStock,
  FilmingLocation,
  EndorsementOffer,
  StudioRelationship,
} from '../types/world';

export const INITIAL_BOX_OFFICE: BoxOfficeItem[] = [
  {
    id: 'bo_1',
    title: 'Avatar: Fire and Ash',
    type: 'Movie',
    currentRank: 1,
    previousRank: 1,
    weeklyGross: 45000000,
    domesticGross: 710000000,
    internationalGross: 1410000000,
    worldwideGross: 2120000000,
    lifetimeGross: 2120000000,
    weeksReleased: 14,
    weeksInRelease: 14,
    grossWorldwide: 2120000000,
    grossDomestic: 710000000,
    grossInternational: 1410000000,
    movement: 'UP',
    trend: 'UP',
    studio: '20th Century Studios',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_2',
    title: 'Avengers: Secret Wars',
    type: 'Movie',
    currentRank: 2,
    previousRank: 2,
    weeklyGross: 38000000,
    domesticGross: 680000000,
    internationalGross: 1300000000,
    worldwideGross: 1980000000,
    lifetimeGross: 1980000000,
    weeksReleased: 10,
    weeksInRelease: 10,
    grossWorldwide: 1980000000,
    grossDomestic: 680000000,
    grossInternational: 1300000000,
    movement: 'UP',
    trend: 'UP',
    studio: 'Marvel Studios',
    genres: ['Action', 'Sci-Fi', 'Superhero'],
    posterUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_3',
    title: 'Dune: Part Three',
    type: 'Movie',
    currentRank: 3,
    previousRank: 3,
    weeklyGross: 22000000,
    domesticGross: 320000000,
    internationalGross: 620000000,
    worldwideGross: 940000000,
    lifetimeGross: 940000000,
    weeksReleased: 8,
    weeksInRelease: 8,
    grossWorldwide: 940000000,
    grossDomestic: 320000000,
    grossInternational: 620000000,
    movement: 'STABLE',
    trend: 'STABLE',
    studio: 'Warner Bros. Pictures',
    genres: ['Sci-Fi', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_4',
    title: 'Gladiator III: Empire of Blood',
    type: 'Movie',
    currentRank: 4,
    previousRank: 5,
    weeklyGross: 18000000,
    domesticGross: 290000000,
    internationalGross: 490000000,
    worldwideGross: 780000000,
    lifetimeGross: 780000000,
    weeksReleased: 6,
    weeksInRelease: 6,
    grossWorldwide: 780000000,
    grossDomestic: 290000000,
    grossInternational: 490000000,
    movement: 'UP',
    trend: 'UP',
    studio: 'Paramount Pictures',
    genres: ['Action', 'Historical', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_5',
    title: 'The Dark Knight Returns',
    type: 'Movie',
    currentRank: 5,
    previousRank: 4,
    weeklyGross: 14000000,
    domesticGross: 450000000,
    internationalGross: 700000000,
    worldwideGross: 1150000000,
    lifetimeGross: 1150000000,
    weeksReleased: 12,
    weeksInRelease: 12,
    grossWorldwide: 1150000000,
    grossDomestic: 450000000,
    grossInternational: 700000000,
    movement: 'DOWN',
    trend: 'DOWN',
    studio: 'DC Studios',
    genres: ['Action', 'Crime', 'Thriller'],
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_6',
    title: 'Stranger Things: Season 5',
    type: 'Series',
    currentRank: 6,
    previousRank: 7,
    weeklyGross: 0,
    domesticGross: 0,
    internationalGross: 0,
    worldwideGross: 0,
    lifetimeGross: 0,
    weeksReleased: 5,
    weeksInRelease: 5,
    grossWorldwide: 0,
    grossDomestic: 0,
    grossInternational: 0,
    movement: 'UP',
    trend: 'UP',
    studio: 'Netflix Studios',
    genres: ['Horror', 'Sci-Fi', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_7',
    title: 'The Last of Us: Season 2',
    type: 'Series',
    currentRank: 7,
    previousRank: 7,
    weeklyGross: 0,
    domesticGross: 0,
    internationalGross: 0,
    worldwideGross: 0,
    lifetimeGross: 0,
    weeksReleased: 7,
    weeksInRelease: 7,
    grossWorldwide: 0,
    grossDomestic: 0,
    grossInternational: 0,
    movement: 'STABLE',
    trend: 'STABLE',
    studio: 'HBO',
    genres: ['Drama', 'Thriller', 'Post-Apocalyptic'],
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop',
  },
  {
    id: 'bo_8',
    title: 'The White Lotus: Season 3',
    type: 'Series',
    currentRank: 8,
    previousRank: 6,
    weeklyGross: 0,
    domesticGross: 0,
    internationalGross: 0,
    worldwideGross: 0,
    lifetimeGross: 0,
    weeksReleased: 9,
    weeksInRelease: 9,
    grossWorldwide: 0,
    grossDomestic: 0,
    grossInternational: 0,
    movement: 'DOWN',
    trend: 'DOWN',
    studio: 'HBO',
    genres: ['Comedy', 'Drama', 'Satire'],
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop',
  },
];

export const INITIAL_STREAMING_PLATFORMS: StreamingPlatform[] = [
  {
    id: 'stream_netflix',
    name: 'Netflix',
    logoUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=150&auto=format&fit=crop',
    color: '#E50914',
    subscribers: '277 Million',
    subscriberBase: 277000000,
    budgetTier: 'Mega',
    genrePrefs: ['Action', 'Drama', 'Thriller'],
    reputation: 95,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_prime',
    name: 'Amazon Prime Video',
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&auto=format&fit=crop',
    color: '#00A8E1',
    subscribers: '220 Million',
    subscriberBase: 220000000,
    budgetTier: 'Mega',
    genrePrefs: ['Action', 'Sci-Fi', 'Comedy'],
    reputation: 88,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_apple',
    name: 'Apple TV+',
    logoUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=150&auto=format&fit=crop',
    color: '#999999',
    subscribers: '50 Million',
    subscriberBase: 50000000,
    budgetTier: 'Major',
    genrePrefs: ['Drama', 'Sci-Fi', 'Thriller'],
    reputation: 90,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_disney',
    name: 'Disney+',
    logoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150&auto=format&fit=crop',
    color: '#113CCF',
    subscribers: '153 Million',
    subscriberBase: 153000000,
    budgetTier: 'Mega',
    genrePrefs: ['Family', 'Fantasy', 'Action'],
    reputation: 85,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_hbomax',
    name: 'HBO Max',
    logoUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150&auto=format&fit=crop',
    color: '#5822B4',
    subscribers: '100 Million',
    subscriberBase: 100000000,
    budgetTier: 'Major',
    genrePrefs: ['Drama', 'Thriller', 'Fantasy'],
    reputation: 92,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_hulu',
    name: 'Hulu',
    logoUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=150&auto=format&fit=crop',
    color: '#1CE783',
    subscribers: '50 Million',
    subscriberBase: 50000000,
    budgetTier: 'Major',
    genrePrefs: ['Comedy', 'Drama', 'Romance'],
    reputation: 75,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_paramount',
    name: 'Paramount+',
    logoUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=150&auto=format&fit=crop',
    color: '#0064FF',
    subscribers: '67 Million',
    subscriberBase: 67000000,
    budgetTier: 'Major',
    genrePrefs: ['Action', 'Thriller', 'Western'],
    reputation: 72,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_peacock',
    name: 'Peacock',
    logoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150&auto=format&fit=crop',
    color: '#00A859',
    subscribers: '34 Million',
    subscriberBase: 34000000,
    budgetTier: 'Mid',
    genrePrefs: ['Comedy', 'Crime', 'Drama'],
    reputation: 65,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_youtube',
    name: 'YouTube',
    logoUrl: 'https://images.unsplash.com/photo-1611162616091-26b21557b4a7?w=150&auto=format&fit=crop',
    color: '#FF0000',
    subscribers: '2.7 Billion',
    subscriberBase: 2700000000,
    budgetTier: 'Mega',
    genrePrefs: ['Any'],
    reputation: 60,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_crunchyroll',
    name: 'Crunchyroll',
    logoUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=150&auto=format&fit=crop',
    color: '#F47521',
    subscribers: '13 Million',
    subscriberBase: 13000000,
    budgetTier: 'Indie',
    genrePrefs: ['Anime', 'Fantasy'],
    reputation: 68,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_mubi',
    name: 'Mubi',
    logoUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=150&auto=format&fit=crop',
    color: '#00263E',
    subscribers: '12 Million',
    subscriberBase: 12,
    budgetTier: 'Mid',
    genrePrefs: ['Drama', 'Comedy'],
    reputation: 70,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
  {
    id: 'stream_roku',
    name: 'The Roku Channel',
    logoUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=150&auto=format&fit=crop',
    color: '#662D91',
    subscribers: '80 Million',
    subscriberBase: 80,
    budgetTier: 'Mid',
    genrePrefs: ['Drama', 'Comedy'],
    reputation: 70,
    status: 'Neutral',
    exclusiveDealsCount: 0,
    moviesLicensed: 0,
    seriesLicensed: 0,
    moneyEarned: 0,
  },
];

export const INITIAL_BANKROLL_OPPORTUNITIES: BankrollOpportunity[] = [
  {
    id: 'bk_1',
    title: 'Neo-Noir Neo City Thriller',
    type: 'Movie',
    budget: 450000,
    weeksRemaining: 8,
    expectedReturnPct: 45,
    risk: 'Medium',
    productionProgress: 15,
    investedAmount: 0,
    isInvested: false,
  },
  {
    id: 'bk_2',
    title: 'Cannes Film Festival Contender Drama',
    type: 'Movie',
    budget: 250000,
    weeksRemaining: 12,
    expectedReturnPct: 80,
    risk: 'High',
    productionProgress: 0,
    investedAmount: 0,
    isInvested: false,
  },
  {
    id: 'bk_3',
    title: 'Cyberpunk Animated Mini-Series',
    type: 'Streaming Original',
    budget: 850000,
    weeksRemaining: 16,
    expectedReturnPct: 35,
    risk: 'Low',
    productionProgress: 40,
    investedAmount: 0,
    isInvested: false,
  },
  {
    id: 'bk_4',
    title: 'Global Sci-Fi Blockbuster Co-Finance',
    type: 'Movie',
    budget: 2500000,
    weeksRemaining: 24,
    expectedReturnPct: 110,
    risk: 'Extreme',
    productionProgress: 10,
    investedAmount: 0,
    isInvested: false,
  },
];

export const INITIAL_TV_STATIONS: TvStation[] = [
  {
    id: 'tv_1',
    name: 'Good Morning America',
    showName: 'GMA Morning Spotlight',
    host: 'Dana Whitfield', // simulated host
    stationType: 'Morning',
    viewerReach: '3.8 Million Viewers',
    viewerBase: 3800000,
    imageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=500&auto=format&fit=crop',
    minFame: 0,
    minMovies: 0,
  },
  {
    id: 'tv_2',
    name: 'Today Show',
    showName: 'Today at NBC',
    host: 'Marcus Bell & Elena Ruiz',
    stationType: 'Morning',
    viewerReach: '3.4 Million Viewers',
    viewerBase: 3400000,
    imageUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&auto=format&fit=crop',
    minFame: 0,
    minMovies: 0,
  },
  {
    id: 'tv_3',
    name: 'Access Hollywood',
    showName: 'Access Daily',
    host: 'Carly Stone',
    stationType: 'Entertainment',
    viewerReach: '2.1 Million Viewers',
    viewerBase: 2100000,
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&auto=format&fit=crop',
    minFame: 300,
    minMovies: 1,
  },
  {
    id: 'tv_4',
    name: 'Entertainment Tonight',
    showName: 'ET Exclusive',
    host: 'Devon Pierce & Ava Lind',
    stationType: 'Entertainment',
    viewerReach: '2.9 Million Viewers',
    viewerBase: 2900000,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop',
    minFame: 500,
    minMovies: 2,
  },
  {
    id: 'tv_5',
    name: 'Jimmy Kimmel Live',
    showName: 'Late Night Comedy Lounge',
    host: 'Rico Santana',
    stationType: 'Late Night',
    viewerReach: '1.9 Million Viewers',
    viewerBase: 1900000,
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop',
    minFame: 800,
    minMovies: 2,
  },
  {
    id: 'tv_6',
    name: 'The Tonight Show',
    showName: 'The Tonight Desk',
    host: 'Leo Marsh',
    stationType: 'Late Night',
    viewerReach: '2.4 Million Viewers',
    viewerBase: 2400000,
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=500&auto=format&fit=crop',
    minFame: 1000,
    minMovies: 3,
  },
  {
    id: 'tv_7',
    name: 'Late Night',
    showName: 'The Late Desk',
    host: 'Samantha Cole',
    stationType: 'Late Night',
    viewerReach: '1.2 Million Viewers',
    viewerBase: 1200000,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=500&auto=format&fit=crop',
    minFame: 800,
    minMovies: 2,
  },
  {
    id: 'tv_8',
    name: '60 Minutes',
    showName: 'CBS 60 Minutes In-Depth',
    host: 'Grant Holloway',
    stationType: 'News',
    viewerReach: '7.5 Million Viewers',
    viewerBase: 7500000,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=500&auto=format&fit=crop',
    minFame: 2000,
    minMovies: 4,
  },
  {
    id: 'tv_9',
    name: 'BBC World',
    showName: 'BBC World News Entertainment',
    host: 'Priya Anand',
    stationType: 'International',
    viewerReach: '12.0 Million Worldwide',
    viewerBase: 12000000,
    imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=500&auto=format&fit=crop',
    minFame: 2500,
    minMovies: 5,
  },
  {
    id: 'tv_10',
    name: 'CNN Entertainment',
    showName: 'CNN Red Carpet Live',
    host: 'Alex Mendez',
    stationType: 'News',
    viewerReach: '4.2 Million Viewers',
    viewerBase: 4200000,
    imageUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=500&auto=format&fit=crop',
    minFame: 1500,
    minMovies: 3,
  },
  // NEW STATIONS
  {
    id: 'tv_11',
    name: 'CBS Mornings',
    showName: 'CBS Morning Edition',
    host: 'Tara Lyons',
    stationType: 'Morning',
    viewerReach: '2.8 Million Viewers',
    viewerBase: 2800000,
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=500&auto=format&fit=crop',
    minFame: 0,
    minMovies: 0,
  },
  {
    id: 'tv_12',
    name: 'The Talk',
    showName: 'The Daytime Circle',
    host: 'Nia Brooks, Carmen Vega, Jules Hart',
    stationType: 'Entertainment',
    viewerReach: '1.6 Million Viewers',
    viewerBase: 1600000,
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=500&auto=format&fit=crop',
    minFame: 600,
    minMovies: 2,
  },
  {
    id: 'tv_13',
    name: 'SportsCenter',
    showName: 'SportsCenter: The Celebrity Athlete Special',
    host: 'Ray Donovan Jr.',
    stationType: 'Sports',
    viewerReach: '3.1 Million Viewers',
    viewerBase: 3100000,
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&auto=format&fit=crop',
    minFame: 1200,
    minMovies: 3,
  },
  {
    id: 'tv_14',
    name: 'E! News',
    showName: 'E! Daily Pop',
    host: 'Kit Marlowe',
    stationType: 'Entertainment',
    viewerReach: '2.2 Million Viewers',
    viewerBase: 2200000,
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500&auto=format&fit=crop',
    minFame: 700,
    minMovies: 2,
  },
  {
    id: 'tv_15',
    name: 'Sky News',
    showName: 'Sky Entertainment Desk',
    host: 'Omar Saleh',
    stationType: 'International',
    viewerReach: '6.0 Million Worldwide',
    viewerBase: 6000000,
    imageUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=500&auto=format&fit=crop',
    minFame: 2200,
    minMovies: 4,
  },
  {
    id: 'tv_16',
    name: 'Extra TV',
    showName: 'Extra: Weekend Edition',
    host: 'Renee Marsh',
    stationType: 'Entertainment',
    viewerReach: '2.4 Million Viewers',
    viewerBase: 2400000,
    imageUrl: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=500&auto=format&fit=crop',
    minFame: 350,
    minMovies: 1,
  },
  {
    id: 'tv_17',
    name: 'Inside Edition',
    showName: 'Inside Edition Primetime',
    host: 'Deborah Norville',
    stationType: 'News',
    viewerReach: '3.9 Million Viewers',
    viewerBase: 3900000,
    imageUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=500&auto=format&fit=crop',
    minFame: 900,
    minMovies: 2,
  },
  {
    id: 'tv_18',
    name: 'The Roundtable',
    showName: 'The Roundtable LA',
    host: 'Wanda Simmons',
    stationType: 'Talk',
    viewerReach: '1.5 Million Viewers',
    viewerBase: 1500000,
    imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&auto=format&fit=crop',
    minFame: 600,
    minMovies: 2,
  },
  {
    id: 'tv_19',
    name: 'Sunrise America',
    showName: 'Sunrise America',
    host: 'Clint Hargrove',
    stationType: 'Morning',
    viewerReach: '4.6 Million Viewers',
    viewerBase: 4600000,
    imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=500&auto=format&fit=crop',
    minFame: 450,
    minMovies: 1,
  },
  {
    id: 'tv_20',
    name: 'CNN Tonight LA',
    showName: 'CNN Tonight: Los Angeles',
    host: 'Andrea Koppel',
    stationType: 'News',
    viewerReach: '2.8 Million Viewers',
    viewerBase: 2800000,
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=500&auto=format&fit=crop',
    minFame: 1300,
    minMovies: 3,
  },
  {
    id: 'tv_21',
    name: 'The Late List',
    showName: 'The Late List with Marcus Rio',
    host: 'Marcus Rio',
    stationType: 'Late Night',
    viewerReach: '1.9 Million Viewers',
    viewerBase: 1900000,
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop',
    minFame: 1100,
    minMovies: 2,
  },
];

export const INITIAL_RADIO_STATIONS: RadioStation[] = [
  {
    id: 'rad_1',
    name: 'Hot 97',
    host: 'Dre James', // simulated host
    stationType: 'HipHop',
    listeners: '3.2 Million Daily Listeners',
    listenerBase: 3200000,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop',
    minFame: 0,
    minMovies: 0,
  },
  {
    id: 'rad_2',
    name: 'KIIS FM',
    host: 'Tori Blake',
    stationType: 'Top40',
    listeners: '4.8 Million Daily Listeners',
    listenerBase: 4800000,
    imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=500&auto=format&fit=crop',
    minFame: 200,
    minMovies: 0,
  },
  {
    id: 'rad_3',
    name: 'BBC Radio 1',
    host: 'Noah Kemp',
    stationType: 'International',
    listeners: '8.5 Million Global Listeners',
    listenerBase: 8500000,
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=500&auto=format&fit=crop',
    minFame: 1500,
    minMovies: 3,
  },
  {
    id: 'rad_4',
    name: 'NPR',
    host: 'Avery Chen',
    stationType: 'News',
    listeners: '5.1 Million Listeners',
    listenerBase: 5100000,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=500&auto=format&fit=crop',
    minFame: 1200,
    minMovies: 2,
  },
  {
    id: 'rad_5',
    name: 'Power 105.1',
    host: 'Miles Carter & Jade Fox',
    stationType: 'HipHop',
    listeners: '4.1 Million Listeners',
    listenerBase: 4100000,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=500&auto=format&fit=crop',
    minFame: 400,
    minMovies: 1,
  },
  {
    id: 'rad_6',
    name: 'Elvis Duran',
    host: 'Ricky Moreno',
    stationType: 'Morning',
    listeners: '3.9 Million Listeners',
    listenerBase: 3900000,
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&auto=format&fit=crop',
    minFame: 600,
    minMovies: 1,
  },
  {
    id: 'rad_7',
    name: 'Howard Stern',
    host: 'Vince Calloway',
    stationType: 'Talk',
    listeners: '2.5 Million Subscribers',
    listenerBase: 2500000,
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop',
    minFame: 2500,
    minMovies: 4,
  },
  {
    id: 'rad_8',
    name: 'Talk Radio 770',
    host: 'Stan Rourke',
    stationType: 'Talk',
    listeners: '1.1 Million Listeners',
    listenerBase: 1100000,
    imageUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=500&auto=format&fit=crop',
    minFame: 900,
    minMovies: 2,
  },
  // NEW STATIONS
  {
    id: 'rad_9',
    name: 'SiriusXM Hits 1',
    host: 'Mia Delacroix',
    stationType: 'Top40',
    listeners: '6.2 Million Subscribers',
    listenerBase: 6200000,
    imageUrl: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=500&auto=format&fit=crop',
    minFame: 1000,
    minMovies: 2,
  },
  {
    id: 'rad_10',
    name: 'iHeartRadio',
    host: 'Jules Fontaine',
    stationType: 'Top40',
    listeners: '10.0 Million Listeners',
    listenerBase: 10000000,
    imageUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=500&auto=format&fit=crop',
    minFame: 1800,
    minMovies: 3,
  },
  {
    id: 'rad_11',
    name: 'LA Talk Live',
    host: 'Gina Park',
    stationType: 'Talk',
    listeners: '2.8 Million Listeners',
    listenerBase: 2800000,
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500&auto=format&fit=crop',
    minFame: 800,
    minMovies: 2,
  },
  {
    id: 'rad_12',
    name: 'Hollywood Morning Mix',
    host: 'Sam Rivera & Chloe Lane',
    stationType: 'Morning',
    listeners: '3.3 Million Listeners',
    listenerBase: 3300000,
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=500&auto=format&fit=crop',
    minFame: 500,
    minMovies: 1,
  },
  {
    id: 'rad_13',
    name: 'Z100 LA',
    host: 'Carla Vee',
    stationType: 'Top40',
    listeners: '2.2 Million Listeners',
    listenerBase: 2200000,
    imageUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=500&auto=format&fit=crop',
    minFame: 300,
    minMovies: 1,
  },
  {
    id: 'rad_14',
    name: "Big Boy's Neighborhood",
    host: 'Big Boy',
    stationType: 'HipHop',
    listeners: '2.8 Million Listeners',
    listenerBase: 2800000,
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&auto=format&fit=crop',
    minFame: 550,
    minMovies: 1,
  },
  {
    id: 'rad_15',
    name: 'The Bert Show AM',
    host: 'Bettina Cross',
    stationType: 'Morning',
    listeners: '1.9 Million Listeners',
    listenerBase: 1900000,
    imageUrl: 'https://images.unsplash.com/photo-1554774853-aae0a22c8aa4?w=500&auto=format&fit=crop',
    minFame: 250,
    minMovies: 1,
  },
  {
    id: 'rad_16',
    name: 'KROQ Drive Time',
    host: 'Stryker',
    stationType: 'Rock',
    listeners: '1.6 Million Listeners',
    listenerBase: 1600000,
    imageUrl: 'https://images.unsplash.com/photo-1499415479124-43c32433a620?w=500&auto=format&fit=crop',
    minFame: 700,
    minMovies: 2,
  },
  {
    id: 'rad_17',
    name: 'ESPN LA Drive',
    host: 'Marcellus Wade',
    stationType: 'Sports',
    listeners: '1.4 Million Listeners',
    listenerBase: 1400000,
    imageUrl: 'https://images.unsplash.com/photo-1461897104016-0b3b00cc82ee?w=500&auto=format&fit=crop',
    minFame: 800,
    minMovies: 2,
  },
  {
    id: 'rad_18',
    name: 'Midnight Confessions',
    host: 'Dr. Velvet Rios',
    stationType: 'Talk',
    listeners: '1.1 Million Listeners',
    listenerBase: 1100000,
    imageUrl: 'https://images.unsplash.com/photo-1519874179391-3ebc752241dd?w=500&auto=format&fit=crop',
    minFame: 1000,
    minMovies: 2,
  },
];

export const INITIAL_SOCIAL_ACCOUNTS: SocialAccount[] = [
  { platform: 'Twitter', handle: '@HollywoodRising', followers: 1250, following: 320, verified: false, monetizationActive: false },
  { platform: 'Facebook', handle: 'OfficialRisingActor', followers: 850, following: 410, verified: false, monetizationActive: false },
  { platform: 'Instagram', handle: '@hollywood_star', followers: 3400, following: 580, verified: false, monetizationActive: false },
  { platform: 'Reddit', handle: 'u/HollywoodActor', followers: 420, following: 45, verified: false, monetizationActive: false },
  { platform: 'YouTube', handle: 'HollywoodRisingVlogs', followers: 1100, following: 88, verified: false, monetizationActive: false },
  { platform: 'Telegram', handle: 't.me/hollywood_updates', followers: 310, following: 12, verified: false, monetizationActive: false },
];

export const INITIAL_SOCIAL_POSTS: SocialPost[] = [
  {
    id: 'post_1',
    authorName: 'Hollywood Pulse',
    authorHandle: '@hollywoodpulse',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop',
    platform: 'Twitter',
    tab: 'NPC_FEED',
    text: 'BREAKING: Box office tracking indicates summer movie ticket sales are up 22%! Streaming wars heat up.',
    likes: 14200,
    comments: 890,
    retweets: 3100,
    shares: 1200,
    timestamp: '2h ago',
    isPlayer: false,
    isNpc: true,
    sentiment: 'Viral',
  },
  {
    id: 'post_2',
    authorName: 'ScreenWire',
    authorHandle: '@screenwire',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop',
    platform: 'Twitter',
    tab: 'NPC_FEED',
    text: 'SAG-AFTRA casting directors report high demand for fresh faces in upcoming action thrillers!',
    likes: 8900,
    comments: 420,
    retweets: 1200,
    shares: 310,
    timestamp: '5h ago',
    isPlayer: false,
    isNpc: true,
    sentiment: 'Positive',
  },
];

export const INITIAL_HIRED_WRITERS: HiredWriter[] = [
  { id: 'w_1', name: 'Liam Vance (Junior Blogger)', tier: 'Low', weeklyCost: 250, postsPerWeek: 3, contractWeeksRemaining: 4, postsThisWeek: 0, qualityBoost: 5, hired: false },
  { id: 'w_2', name: 'Sophia Sterling (PR Specialist)', tier: 'Medium', weeklyCost: 750, postsPerWeek: 5, contractWeeksRemaining: 4, postsThisWeek: 0, qualityBoost: 15, hired: false },
  { id: 'w_3', name: 'Marcus Sterling (Veteran Hollywood Ghostwriter)', tier: 'Elite', weeklyCost: 2500, postsPerWeek: 10, contractWeeksRemaining: 4, postsThisWeek: 0, qualityBoost: 35, hired: false },
];

export const INITIAL_LAWYERS: LawFirm[] = [
  {
    id: 'firm_1',
    name: 'Blackstone & Pierce',
    logoUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=150&auto=format&fit=crop',
    bio: 'Beverly Hills premier entertainment litigation firm specializing in actor contracts & copyright disputes.',
    winRate: 94,
    specialty: 'Contract Disputes & Intellectual Property',
    retainerFee: 15000,
    tier: 'Ultra Luxury',
    isHired: false,
  },
  {
    id: 'firm_2',
    name: 'Sterling Legal Group',
    logoUrl: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=150&auto=format&fit=crop',
    bio: 'High-octane defense attorneys protecting celebrity reputations and managing press leaks.',
    winRate: 88,
    specialty: 'Defamation & Media Law',
    retainerFee: 8500,
    tier: 'Elite',
    isHired: false,
  },
  {
    id: 'firm_3',
    name: 'Kingsley & Hart',
    logoUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=150&auto=format&fit=crop',
    bio: 'A powerhouse in film studio arbitration and production labor disputes.',
    winRate: 82,
    specialty: 'Studio Arbitration & Guild Law',
    retainerFee: 6000,
    tier: 'Elite',
    isHired: false,
  },
  {
    id: 'firm_4',
    name: 'Dominion Law Partners',
    logoUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=150&auto=format&fit=crop',
    bio: 'Corporate entertainment lawyers handling multi-million dollar endorsement contracts.',
    winRate: 79,
    specialty: 'Endorsements & Brand Licensing',
    retainerFee: 4500,
    tier: 'Standard',
    isHired: false,
  },
  {
    id: 'firm_5',
    name: 'Vanguard Legal',
    logoUrl: 'https://images.unsplash.com/photo-1436450412740-6b988f486c6b?w=150&auto=format&fit=crop',
    bio: 'Aggressive trial lawyers representing actors in breach of contract cases.',
    winRate: 75,
    specialty: 'Civil Litigation & Breach of Contract',
    retainerFee: 3500,
    tier: 'Standard',
    isHired: false,
  },
  {
    id: 'firm_6',
    name: 'Whitmore & Associates',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop',
    bio: 'Affordable legal counsel for rising actors navigating union rules & talent contracts.',
    winRate: 70,
    specialty: 'Talent Contracts & Union Representation',
    retainerFee: 2000,
    tier: 'Standard',
    isHired: false,
  },
  {
    id: 'firm_7',
    name: 'Ashford Global Law',
    logoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop',
    bio: 'International entertainment law firm handling foreign box office licensing and distribution deals.',
    winRate: 91,
    specialty: 'International Film Distribution',
    retainerFee: 12000,
    tier: 'Ultra Luxury',
    isHired: false,
  },
];

export const INITIAL_CRYPTO_COINS: CryptoCoin[] = [
  { id: 'c_btc', name: 'Bitcoin', symbol: 'BTC', price: 92450, change24h: 3.4, marketCap: 1800000000000, holdings: 0, news: 'Institutional ETF inflows reach record $1.2B this week.' },
  { id: 'c_eth', name: 'Ethereum', symbol: 'ETH', price: 3450, change24h: -1.2, marketCap: 410000000000, holdings: 0, news: 'Staking yields hold steady at 3.8% APY.' },
  { id: 'c_sol', name: 'Solana', symbol: 'SOL', price: 185.2, change24h: 8.4, marketCap: 86000000000, holdings: 0, news: 'Hollywood NFT ticketing dapp volume surges 40%.' },
  { id: 'c_holly', name: 'HollywoodCoin', symbol: 'HWLN', price: 14.5, change24h: 12.8, marketCap: 850000000, holdings: 0, news: 'Major studio announces film financing integration with HWLN.' },
  { id: 'c_star', name: 'StarToken', symbol: 'STAR', price: 4.2, change24h: 5.6, marketCap: 320000000, holdings: 0, news: 'A-list celebrities endorse STAR fan token governance.' },
  { id: 'c_cinema', name: 'CinemaCash', symbol: 'CCSH', price: 0.85, change24h: -4.5, marketCap: 95000000, holdings: 0, news: 'Box office rewards integration delayed until Q4.' },
  { id: 'c_film', name: 'FilmChain', symbol: 'FLM', price: 2.10, change24h: 6.1, marketCap: 140000000, holdings: 0, news: 'DeFi royalty payouts distributed to indie producers.' },
  { id: 'c_meta', name: 'MetaStudio', symbol: 'MST', price: 0.42, change24h: -2.3, marketCap: 45000000, holdings: 0, news: 'VR stage production platform launches beta.' },
  { id: 'c_oscar', name: 'OscarDao', symbol: 'OSCR', price: 12.80, change24h: 18.2, marketCap: 210000000, holdings: 0, news: 'Award season predictions drive viral trading volume.' },
  { id: 'c_doge', name: 'Dogecoin', symbol: 'DOGE', price: 0.16, change24h: 4.2, marketCap: 23000000000, holdings: 0, news: 'Meme rally continues as Hollywood premiere accepts DOGE.' },
  { id: 'c_shib', name: 'Shiba Inu', symbol: 'SHIB', price: 0.000024, change24h: -1.1, marketCap: 14000000000, holdings: 0, news: 'Token burn rate increases 120%.' },
  { id: 'c_red', name: 'RedCarpet', symbol: 'RCR', price: 1.15, change24h: 9.3, marketCap: 68000000, holdings: 0, news: 'VIP premiere access granted to top token holders.' },
  { id: 'c_vox', name: 'VoiceToken', symbol: 'VOX', price: 0.95, change24h: 3.1, marketCap: 52000000, holdings: 0, news: 'Voice actors guild explores blockchain royalty tracking.' },
  { id: 'c_pix', name: 'PixelActor', symbol: 'PIX', price: 3.40, change24h: -5.4, marketCap: 110000000, holdings: 0, news: 'AI character avatar generation marketplace expands.' },
  { id: 'c_tape', name: 'TapeVault', symbol: 'TAPE', price: 0.65, change24h: 1.8, marketCap: 38000000, holdings: 0, news: 'Archival film preservation DAO votes on new acquisitions.' },
  { id: 'c_gem', name: 'GemStar', symbol: 'GEM', price: 8.90, change24h: 14.2, marketCap: 390000000, holdings: 0, news: 'Luxury brand endorsements linked to GEM wallet perks.' },
  { id: 'c_script', name: 'ScriptCoin', symbol: 'SCRIPT', price: 0.35, change24h: 0.8, marketCap: 28000000, holdings: 0, news: 'Screenwriters DAO funds 3 new indie pilots.' },
  { id: 'c_mycoin', name: 'My Personal Coin', symbol: 'ME', price: 1.0, change24h: 0, marketCap: 1000000, holdings: 0, isMyCoin: true, news: 'Created by player to tokenize personal brand and fan perks.' },
];

export const INITIAL_CRYPTO_WHALES: CryptoWhale[] = [
  { id: 'wh_1', name: 'Satoshi_Vanderbilt', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop', winRatePct: 88, totalProfit: 14500000, copyTradeActive: false },
  { id: 'wh_2', name: 'Hollywood_Whale', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop', winRatePct: 76, totalProfit: 8200000, copyTradeActive: false },
  { id: 'wh_3', name: 'CryptoDirector', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop', winRatePct: 69, totalProfit: 4100000, copyTradeActive: false },
  { id: 'wh_4', name: 'A24_Hodler', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop', winRatePct: 81, totalProfit: 9800000, copyTradeActive: false },
  { id: 'wh_5', name: 'BeverlyHills_Bull', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop', winRatePct: 74, totalProfit: 6200000, copyTradeActive: false },
];

export const INITIAL_STAR_STOCKS: StarStock[] = [
  { id: 'st_1', name: 'The Walt Disney Company', ticker: 'DIS', ceo: 'Bob Iger', price: 114.5, changePct: 1.8, marketCap: '$210B', sharesOwned: 0, sector: 'Entertainment', history: 'Founded in 1923, global powerhouse in animation, theme parks & streaming.', recentMovies: ['Avatar 3', 'Inside Out 2'], recentSeries: ['The Mandalorian', 'Loki'], news: 'Q3 streaming profitability beat consensus expectations.' },
  { id: 'st_2', name: 'Netflix Inc.', ticker: 'NFLX', ceo: 'Ted Sarandos', price: 680.2, changePct: 3.4, marketCap: '$290B', sharesOwned: 0, sector: 'Streaming', history: 'Pioneered SVOD streaming and global original production.', recentMovies: ['Glass Onion', 'Red Notice 2'], recentSeries: ['Stranger Things S5', 'Squid Game S2'], news: 'Subscriber additions set new international records.' },
  { id: 'st_3', name: 'Warner Bros. Discovery', ticker: 'WBD', ceo: 'David Zaslav', price: 8.4, changePct: -2.1, marketCap: '$21B', sharesOwned: 0, sector: 'Studios', history: 'Historic studio behind DC, Harry Potter & HBO prestige television.', recentMovies: ['Dune: Part Two', 'Godzilla x Kong'], recentSeries: ['House of the Dragon S2', 'The Last of Us S2'], news: 'Debt reduction campaign continues ahead of slate rollout.' },
  { id: 'st_4', name: 'Paramount Global', ticker: 'PARA', ceo: 'Shari Redstone', price: 12.1, changePct: 0.5, marketCap: '$8B', sharesOwned: 0, sector: 'Studios', history: 'Home of Star Trek, Mission Impossible & CBS Sports.', recentMovies: ['Gladiator II', 'Sonic 3'], recentSeries: ['Yellowstone', 'Tulsa King'], news: 'Merger negotiation talks near final closing.' },
  { id: 'st_5', name: 'Sony Group Corp', ticker: 'SONY', ceo: 'Kenichiro Yoshida', price: 88.6, changePct: 1.2, marketCap: '$110B', sharesOwned: 0, sector: 'Conglomerate', history: 'Japanese tech and entertainment giant producing Spider-Man & PlayStation.', recentMovies: ['Spider-Man: Beyond Spider-Verse', 'Bad Boys 4'], recentSeries: ['Twisted Metal', 'The Boys'], news: 'Sensor tech and film production divisions report double digit growth.' },
  { id: 'st_6', name: 'Lions Gate Entertainment', ticker: 'LGF.A', ceo: 'Jon Feltheimer', price: 9.8, changePct: -0.8, marketCap: '$2.3B', sharesOwned: 0, sector: 'Indie Studio', history: 'Leading independent studio behind John Wick & The Hunger Games.', recentMovies: ['Ballerina', 'The Crow'], recentSeries: ['Ghosts', 'Power Book'], news: 'Studio and STARZ spin-off separation finalized.' },
  { id: 'st_7', name: 'IMAX Corporation', ticker: 'IMAX', ceo: 'Richard Gelfond', price: 18.2, changePct: 4.1, marketCap: '$980M', sharesOwned: 0, sector: 'Exhibition', history: 'Large-format premium cinema technology provider operating globally.', recentMovies: ['Oppenheimer IMAX Edition', 'Dune 2 IMAX'], recentSeries: [], news: 'Record weekend box office share from premium screens.' },
  { id: 'st_8', name: 'Cinemark Holdings', ticker: 'CNK', ceo: 'Sean Gamble', price: 22.4, changePct: 2.2, marketCap: '$2.7B', sharesOwned: 0, sector: 'Exhibition', history: 'Major theatrical exhibition chain across North and South America.', recentMovies: ['Summer Blockbuster Slate'], recentSeries: [], news: 'Concession sales per patron reach all-time high.' },
  { id: 'st_9', name: 'Apple Inc.', ticker: 'AAPL', ceo: 'Tim Cook', price: 225.4, changePct: 1.1, marketCap: '$3.4T', sharesOwned: 0, sector: 'Tech Giant', history: 'Tech innovator behind iPhone, Mac, and Apple TV+ prestige originals.', recentMovies: ['Killers of the Flower Moon', 'Napoleon'], recentSeries: ['Severance S2', 'Ted Lasso'], news: 'Apple TV+ awards budget increased for upcoming season.' },
  { id: 'st_10', name: 'Amazon.com Inc.', ticker: 'AMZN', ceo: 'Andy Jassy', price: 188.5, changePct: 2.5, marketCap: '$1.9T', sharesOwned: 0, sector: 'Tech Giant', history: 'Global e-commerce and cloud giant powering Prime Video & MGM Studios.', recentMovies: ['Road House', 'The Idea of You'], recentSeries: ['Rings of Power S2', 'Reacher'], news: 'Prime Video advertising rollout generates higher than expected revenue.' },
  { id: 'st_11', name: 'AMC Entertainment', ticker: 'AMC', ceo: 'Adam Aron', price: 4.8, changePct: -3.2, marketCap: '$1.5B', sharesOwned: 0, sector: 'Exhibition', history: 'World largest movie theater chain with active retail shareholder base.', recentMovies: ['Concert Film Events'], recentSeries: [], news: 'Popcorn product line expands to grocery retailers nationwide.' },
  { id: 'st_12', name: 'Roku Inc.', ticker: 'ROKU', ceo: 'Anthony Wood', price: 62.1, changePct: -1.5, marketCap: '$8.8B', sharesOwned: 0, sector: 'Streaming Platform', history: 'Leading streaming hardware and free ad-supported platform provider.', recentMovies: ['Roku Originals'], recentSeries: ['Weird: The Al Yankovic Story'], news: 'Active accounts exceed 80 million globally.' },
  { id: 'st_13', name: 'Spotify Technology', ticker: 'SPOT', ceo: 'Daniel Ek', price: 310.0, changePct: 4.5, marketCap: '$62B', sharesOwned: 0, sector: 'Audio & Podcast', history: 'Dominant global music and podcast streaming service.', recentMovies: [], recentSeries: ['Hollywood Insider Podcasts'], news: 'Podcast monetization and audiobook expansion drives record profits.' },
  { id: 'st_14', name: 'Hasbro Inc.', ticker: 'HAS', ceo: 'Chris Cocks', price: 61.5, changePct: 0.9, marketCap: '$8.5B', sharesOwned: 0, sector: 'Toys & IP', history: 'Owner of Transformers, Dungeons & Dragons, and GI Joe franchises.', recentMovies: ['Transformers One'], recentSeries: ['D&D Animated Series'], news: 'Licensing agreements signed for 3 new feature adaptations.' },
  { id: 'st_15', name: 'Mattel Inc.', ticker: 'MAT', ceo: 'Ynon Kreiz', price: 18.9, changePct: 1.4, marketCap: '$6.5B', sharesOwned: 0, sector: 'Toys & IP', history: 'Toy titan behind Barbie, Hot Wheels, and Masters of the Universe.', recentMovies: ['Barbie Universe Film'], recentSeries: ['Hot Wheels Challenge'], news: 'Mattel Films announces 14 live-action projects in development.' },
];

export const INITIAL_FILMING_LOCATIONS: FilmingLocation[] = [
  { id: 'loc_1', country: 'United States', city: 'Los Angeles, California', taxIncentivePct: 25, permitCost: 5000, weatherRating: 95, travelCost: 1000, flagUrl: '🇺🇸' },
  { id: 'loc_2', country: 'United States', city: 'Atlanta, Georgia', taxIncentivePct: 30, permitCost: 3500, weatherRating: 85, travelCost: 1500, flagUrl: '🇺🇸' },
  { id: 'loc_3', country: 'United Kingdom', city: 'London, England', taxIncentivePct: 34, permitCost: 6500, weatherRating: 65, travelCost: 4500, flagUrl: '🇬🇧' },
  { id: 'loc_4', country: 'Canada', city: 'Vancouver, BC', taxIncentivePct: 35, permitCost: 3000, weatherRating: 75, travelCost: 2500, flagUrl: '🇨🇦' },
  { id: 'loc_5', country: 'New Zealand', city: 'Wellington & Auckland', taxIncentivePct: 40, permitCost: 4000, weatherRating: 80, travelCost: 7500, flagUrl: '🇳🇿' },
  { id: 'loc_6', country: 'Australia', city: 'Sydney, New South Wales', taxIncentivePct: 30, permitCost: 4500, weatherRating: 90, travelCost: 8000, flagUrl: '🇦🇺' },
  { id: 'loc_7', country: 'France', city: 'Paris', taxIncentivePct: 30, permitCost: 7000, weatherRating: 75, travelCost: 5000, flagUrl: '🇫🇷' },
  { id: 'loc_8', country: 'Italy', city: 'Rome & Amalfi Coast', taxIncentivePct: 40, permitCost: 6000, weatherRating: 88, travelCost: 5200, flagUrl: '🇮🇹' },
  { id: 'loc_9', country: 'Japan', city: 'Tokyo & Kyoto', taxIncentivePct: 20, permitCost: 8000, weatherRating: 82, travelCost: 6500, flagUrl: '🇯🇵' },
  { id: 'loc_10', country: 'Ireland', city: 'Dublin & Wicklow Mountains', taxIncentivePct: 32, permitCost: 3200, weatherRating: 60, travelCost: 4800, flagUrl: '🇮🇪' },
];

export const INITIAL_ENDORSEMENT_OFFERS: EndorsementOffer[] = [
  { id: 'end_1', brandName: 'Beverly Hills Local Bistro', category: 'Local', payPerYear: 2600, durationYears: 1, requirements: '1 Social Media Tag/Month', isSigned: false },
  { id: 'end_2', brandName: 'California Urban Apparel', category: 'Regional', payPerYear: 7800, durationYears: 1, requirements: 'Wear apparel during press interviews', isSigned: false },
  { id: 'end_3', brandName: 'Rolex Geneva', category: 'Luxury', payPerYear: 65000, durationYears: 2, requirements: 'Red carpet watch endorsement & 15,000 Fans required', isSigned: false },
  { id: 'end_4', brandName: 'Nike Athletics', category: 'Global', payPerYear: 42000, durationYears: 2, requirements: 'Commercial shoot & 8,000 Fans required', isSigned: false },
  { id: 'end_5', brandName: 'Apple Inc.', category: 'Global', payPerYear: 120000, durationYears: 3, requirements: 'Exclusive Apple device usage & 25,000 Fans required', isSigned: false },
];

export const INITIAL_STUDIO_RELATIONSHIPS: StudioRelationship[] = [
  { id: 'std_1', studioName: 'Warner Bros. Pictures', logoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 50 },
  { id: 'std_2', studioName: 'Universal Pictures', logoUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 50 },
  { id: 'std_3', studioName: 'Paramount Pictures', logoUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 50 },
  { id: 'std_4', studioName: 'A24', logoUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=100&auto=format&fit=crop', relationshipLevel: 'Trusted', points: 65 },
  { id: 'std_5', studioName: 'Marvel Studios', logoUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 45 },
  { id: 'std_6', studioName: '20th Century Studios', logoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 50 },
  { id: 'std_7', studioName: 'Sony Pictures', logoUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 50 },
  { id: 'std_8', studioName: 'Lionsgate Films', logoUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=100&auto=format&fit=crop', relationshipLevel: 'Neutral', points: 50 },
];
